const ReactQueryKeys = {
  CREATE_ADMIN_PROFILE: 'CREATE_ADMIN_PROFILE',
  CREATE_DRIVER_PROFILE: 'CREATE_DRIVER_PROFILE',
  ADMIN_SIGN_IN: 'ADMIN_SIGN_IN',
  DRIVER_SIGN_IN: 'DRIVER_SIGN_IN',
  GET_ALL_DRIVERS: 'GET_ALL_DRIVERS',
  GET_ALL_VEHIClE: 'GET_ALL_VEHIClES',
  GET_TRIP_LOGS: 'GET_TRIP_LOGS',
  UPDATE_DRIVER_PROFILE: 'UPDATE_DRIVER_PROFILE',
  UPDATE_VEHICLE_DATA: 'UPDATE_VEHICLE_DATA',
  CREATE_VEHICLE_DATA: 'CREATE_VEHICLE_DATA',
  START_TRIP: 'START_TRIP',
  END_TRIP: 'END_TRIP',
};

export default ReactQueryKeys;
